version: "3.9"
services:
  api:
    image: myapi:latest
    ports:
      - "8000:8000"
    depends_on:
      fast_db:
        condition: service_healthy

  fast_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/Skeesh/Desktop/SKEESH/exercises/Docker/fast:/var/lib/posgresql/data
      - C:/Users/Skeesh/Desktop/SKEESH/exercises/Docker/backup/fastapi.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d fastapi'"]
      interval: 5s
      timeout: 20s
      retries: 5
